#!/usr/bin/env node
// Generates the Apache/LiteSpeed .htaccess for Hostinger from infra/template.yaml, so the routing, redirects and
// security headers can never drift from the approved CloudFront definition (same idea as scripts/vercel-config.js).
//
//   node scripts/htaccess-config.js --profile staging --out dist/.htaccess    write the file (npm run build:hostinger)
//   node scripts/htaccess-config.js --profile production                      print it (not deployed anywhere yet)
//
// Two profiles, because the same rules serve two different jobs:
//   staging     a review copy on a temporary Hostinger host. Adds "X-Robots-Tag: noindex, nofollow" and uses a SHORT
//               HSTS (max-age=300, no includeSubDomains/preload): a 2-year preload HSTS on an unknown throw-away
//               domain could lock browsers out of sibling sites on the same Hostinger account.
//   production  the security headers of infra/template.yaml, indexable, with ONE owner-approved difference: HSTS is
//               max-age=31536000 only (no includeSubDomains/preload), so it cannot force HTTPS onto other subdomains
//               of the domain (e.g. inventory.) or become hard to undo. infra/template.yaml itself is unchanged.
//
// The file is written into dist/ ONLY by `npm run build:hostinger`. The normal `npm run build` (used by Vercel and the
// S3 sync) never contains it, so a public S3 bucket or Vercel deployment can never end up serving an .htaccess.
//
// Also exports simulateApache(), a small model of mod_rewrite (per-directory context, including the internal
// re-injection after a rewrite) that scripts/verify.js uses to prove these rules route every URL like the
// CloudFront Function. The real Apache behaviour is checked separately against a running server.
// Zero dependencies; read-only apart from writing the --out file.

"use strict";

const fs = require("fs");
const path = require("path");
const { loadRouting, loadSecurityHeaders } = require("./vercel-config");

const PROFILES = ["staging", "production"];
const STAGING_HSTS = "max-age=300";
const PRODUCTION_HSTS = "max-age=31536000";
const NOINDEX = "noindex, nofollow";

// Only the client's ORIGINAL request line contains ".html" in its path. Apache re-runs .htaccess after an internal
// rewrite (/about-us/ -> about.html); without this guard the .html -> pretty redirect would fire again and loop.
const ORIGINAL_HTML_REQUEST = "%{THE_REQUEST} ^[A-Z]+\\s[^?\\s]*\\.html[?\\s]";

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const alt = (list) => `(${list.map(esc).join("|")})`;

function buildHtaccess(profile = "staging") {
  if (!PROFILES.includes(profile)) throw new Error(`Unknown profile "${profile}" (use ${PROFILES.join(" or ")})`);
  const { special, same, legacy } = loadRouting();
  const headers = loadSecurityHeaders().map((h) =>
    h.key === "Strict-Transport-Security" ? { key: h.key, value: profile === "staging" ? STAGING_HSTS : PRODUCTION_HSTS } : h
  );
  if (profile === "staging") headers.push({ key: "X-Robots-Tag", value: NOINDEX });

  const L = [];
  const add = (...lines) => L.push(...lines);

  add(
    "# SFR Motors Ltd - Apache/LiteSpeed rules for Hostinger.",
    "# GENERATED by scripts/htaccess-config.js from infra/template.yaml - do not edit by hand.",
    `# Profile: ${profile}${profile === "staging" ? " (noindex, short HSTS; review copy only)" : ""}`,
    "# Deploy at the DOCUMENT ROOT of its own (sub)domain: every redirect and asset link is root-relative.",
    "",
    "DirectoryIndex index.html",
    "Options -Indexes",
    "AddDefaultCharset UTF-8",
    "",
    "# 403 (a directory such as /assets/) and 404 both show the dedicated, noindex 404 page.",
    "ErrorDocument 403 /404.html",
    "ErrorDocument 404 /404.html",
    "",
    "<IfModule mod_mime.c>",
    "  AddType image/avif .avif",
    "  AddType image/webp .webp",
    "  AddType font/woff2 .woff2",
    "</IfModule>",
    "",
    "<IfModule mod_deflate.c>",
    "  AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript text/plain application/xml image/svg+xml",
    "</IfModule>",
    "",
    "RewriteEngine On",
    "",
    "# The host without a leading www., kept for the redirects below so www + a legacy/.html URL is ONE hop (like CloudFront).",
    "RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]",
    "RewriteRule ^ - [E=SFR_HOST:%1]",
    "RewriteCond %{HTTP_HOST} !^www\\. [NC]",
    "RewriteRule ^ - [E=SFR_HOST:%{HTTP_HOST}]",
    "",
    "# 1. Legacy WordPress URLs (with or without a trailing slash) -> 301.",
  );
  for (const [from, to] of Object.entries(legacy)) {
    add(`RewriteRule ^${esc(from.slice(1))}/?$ https://%{ENV:SFR_HOST}${to} [R=301,L]`);
  }

  add("", "# 2. /index.html -> / (the Home page has one URL).");
  add(`RewriteCond ${ORIGINAL_HTML_REQUEST}`, "RewriteRule ^index\\.html$ https://%{ENV:SFR_HOST}/ [R=301,L]");

  add("", "# 3. /<file>.html -> 301 -> /<slug>/ (the pretty path is the one primary URL).");
  for (const [slug, file] of Object.entries(special)) {
    add(`RewriteCond ${ORIGINAL_HTML_REQUEST}`, `RewriteRule ^${esc(file)}\\.html$ https://%{ENV:SFR_HOST}/${slug}/ [R=301,L]`);
  }
  add(`RewriteCond ${ORIGINAL_HTML_REQUEST}`, `RewriteRule ^${alt(same)}\\.html$ https://%{ENV:SFR_HOST}/$1/ [R=301,L]`);

  add(
    "",
    "# 4. www -> apex in one hop (any other path, query string kept).",
    "RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]",
    "RewriteRule ^ https://%1%{REQUEST_URI} [R=301,L]",
    "",
    "# 5. HTTP -> HTTPS. The X-Forwarded-Proto test stops a redirect loop if Hostinger terminates TLS in front of the server.",
    "RewriteCond %{HTTPS} !=on",
    "RewriteCond %{HTTP:X-Forwarded-Proto} !=https",
    "RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]",
    "",
    "# 6. Pretty paths (with or without a trailing slash) are served from their .html file; the URL in the browser stays pretty.",
  );
  for (const [slug, file] of Object.entries(special)) add(`RewriteRule ^${esc(slug)}/?$ ${file}.html [L]`);
  add(`RewriteRule ^${alt(same)}/?$ $1.html [L]`);
  // /mobile-tyre-fitting: owner-approved live fix. With a trailing slash it 301s to the slash-less URL, which serves mobile-tyre-fitting.html.
  add("RewriteRule ^mobile-tyre-fitting/$ /mobile-tyre-fitting [R=301,L]", "RewriteRule ^mobile-tyre-fitting/?$ mobile-tyre-fitting.html [L]");

  add("", "<IfModule mod_headers.c>");
  add("  # Security headers, from the ResponseHeadersPolicy in infra/template.yaml (\"always\" = also on redirects and the 404 page).");
  for (const h of headers) add(`  Header always set ${h.key} "${h.value}"`);
  add(
    "",
    "  # Caching, same policy as infra/deploy-site.sh: hashed/static assets for a year, pages for 5 minutes, crawler files for an hour.",
    "  # assets/js/tyre-calculator.js is not content-hashed, so it is left to revalidate.",
    '  <FilesMatch "\\.html$">',
    '    Header set Cache-Control "public, max-age=300, must-revalidate"',
    "  </FilesMatch>",
    '  <FilesMatch "\\.(avif|webp|jpe?g|png|svg|woff2)$">',
    '    Header set Cache-Control "public, max-age=31536000, immutable"',
    "  </FilesMatch>",
    '  <FilesMatch "^(main|analytics)\\.[0-9a-f]{8}\\.(css|js)$">',
    '    Header set Cache-Control "public, max-age=31536000, immutable"',
    "  </FilesMatch>",
    '  <FilesMatch "^(robots\\.txt|sitemap\\.xml|favicon\\.ico)$">',
    '    Header set Cache-Control "public, max-age=3600"',
    "  </FilesMatch>",
    "</IfModule>",
    ""
  );
  return L.join("\n");
}

// ---------------------------------------------------------------------------------------------------------------------
// A small mod_rewrite model, enough for the directives above (RewriteCond / RewriteRule, per-directory context).
//   simulateApache(htaccess, { host, https, forwardedProto, uri, query }, { hasFile, isDir })
//   -> { redirect: "https://host/path" } | { file: "/x.html" } | { notFound: true } | { forbidden: true }
// After a non-redirect rewrite Apache restarts the per-directory rules with the new URL (re-injection); so does this.
// ---------------------------------------------------------------------------------------------------------------------
function parseRewrite(htaccess) {
  const items = [];
  let conds = [];
  for (const raw of htaccess.split("\n")) {
    const line = raw.trim();
    if (line.startsWith("RewriteCond ")) {
      const m = line.match(/^RewriteCond\s+(\S+)\s+(\S+)(?:\s+\[([^\]]*)\])?$/);
      conds.push({ test: m[1], pattern: m[2], flags: (m[3] || "").split(",") });
    } else if (line.startsWith("RewriteRule ")) {
      const m = line.match(/^RewriteRule\s+(\S+)\s+(\S+)(?:\s+\[([^\]]*)\])?$/);
      items.push({ conds, pattern: m[1], subst: m[2], flags: (m[3] || "").split(",").filter(Boolean) });
      conds = [];
    }
  }
  return items;
}

function simulateApache(htaccess, req, fsInfo) {
  const rules = parseRewrite(htaccess);
  const env = {};
  const originalPath = req.uri;
  const theRequest = `GET ${originalPath}${req.query ? "?" + req.query : ""} HTTP/1.1`;
  let uri = originalPath.replace(/^\//, "");

  const variable = (name) => {
    if (name === "HTTP_HOST") return req.host || "";
    if (name === "THE_REQUEST") return theRequest;
    if (name === "HTTPS") return req.https ? "on" : "off";
    if (name === "REQUEST_URI") return "/" + uri;
    if (name === "HTTP:X-Forwarded-Proto") return req.forwardedProto || "";
    if (name.startsWith("ENV:")) return env[name.slice(4)] || "";
    throw new Error(`simulateApache does not model %{${name}}`);
  };
  const expand = (text, ruleCaps, condCaps) =>
    text
      .replace(/%\{([^}]+)\}/g, (_, name) => variable(name))
      .replace(/%(\d)/g, (_, n) => (condCaps && condCaps[Number(n)]) || "")
      .replace(/\$(\d)/g, (_, n) => (ruleCaps && ruleCaps[Number(n)]) || "");

  for (let pass = 0; pass < 10; pass++) {
    let restart = false;
    for (const rule of rules) {
      const ruleMatch = new RegExp(rule.pattern).exec(uri);
      if (!ruleMatch) continue;
      let condCaps = null;
      let ok = true;
      for (const cond of rule.conds) {
        const negate = cond.pattern.startsWith("!");
        let pattern = negate ? cond.pattern.slice(1) : cond.pattern;
        const tested = expand(cond.test, ruleMatch, condCaps);
        let matched;
        if (pattern.startsWith("=")) matched = tested === pattern.slice(1);
        else {
          const m = new RegExp(pattern, cond.flags.includes("NC") ? "i" : "").exec(tested);
          matched = Boolean(m);
          if (m && !negate) condCaps = m;
        }
        if (matched === negate) { ok = false; break; }
      }
      if (!ok) continue;

      const target = expand(rule.subst, ruleMatch, condCaps);
      for (const flag of rule.flags.filter((f) => f.startsWith("E="))) {
        const [name, ...value] = flag.slice(2).split(":");
        env[name] = expand(value.join(":"), ruleMatch, condCaps);
      }
      const redirect = rule.flags.find((f) => /^R(=\d+)?$/.test(f));
      if (redirect) {
        return { redirect: target + (target.includes("?") || !req.query ? "" : "?" + req.query) };
      }
      if (target !== "-") {
        uri = target.replace(/^\//, "");
        if (rule.flags.includes("L")) { restart = true; break; }
      } else if (rule.flags.includes("L")) break;
    }
    if (!restart) break;
  }

  const served = uri === "" ? "index.html" : uri;
  if (fsInfo.hasFile(served)) return { file: "/" + served };
  if (fsInfo.isDir(uri)) return { forbidden: true };
  return { notFound: true };
}

module.exports = { buildHtaccess, simulateApache, PROFILES };

if (require.main === module) {
  const arg = (name) => { const i = process.argv.indexOf(name); return i === -1 ? null : process.argv[i + 1]; };
  const profile = arg("--profile") || "staging";
  const text = buildHtaccess(profile);
  const out = arg("--out");
  if (out) {
    const target = path.resolve(out);
    fs.writeFileSync(target, text);
    console.log(`Wrote ${path.relative(process.cwd(), target)} (profile: ${profile}, ${text.split("\n").length} lines)`);
  } else {
    process.stdout.write(text);
  }
}
